=== codinStruct/codinStruct-content/structure.dtd
<!ELEMENT langs (lang*)>
<!-- Represents a programming language -->
<!ELEMENT lang EMPTY>
<!ATTLIST lang
    title CDATA #REQUIRED
    path CDATA #REQUIRED
>
<!ELEMENT categories (category*)>
<!-- Categories belonging to a language -->
<!ELEMENT category (page*)>
<!ATTLIST category
    title CDATA #REQUIRED
    path CDATA #REQUIRED
>
<!-- Pages belonging to a category -->
<!ELEMENT pages (page*)>
<!ELEMENT page EMPTY>
<!ATTLIST page
    title CDATA #REQUIRED
    path CDATA #REQUIRED
>

=== codinStruct/codinStruct-content/Content/C/Basico/pages.xml
<!DOCTYPE pages SYSTEM "../../../structure.dtd">

<pages>
    <page title="Introdução" path="introducao/introducao.md"></page>
    <page title="Primeiro programa" path="primeiro_programa/primeiro_programa.md"></page>
    <page title="Diretiva #include" path="diretiva_include/diretiva_include.md"></page>
    <page title="Funções" path="funcoes/funcoes.md"></page>
    <page title="Variáveis" path="variaveis/variaveis.md"></page>
    <page title="Tipos fundamentais básicos" path="tipos/tipos.md"></page>
    <page title="Tabelas de tipos fundamentais" path="tipos/tabelas.md"></page>
    <page title="Saída básica" path="entrada_e_saida/saida.md"></page>
</pages>
